# docker-compose.yml
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    command: --secure-file-priv=""
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: cs348_project
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d
      - ./cleanedsports.csv:/docker-entrypoint-initdb.d/cleanedsports.csv
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  data-loader:
    image: node:18-alpine
    container_name: data-loader
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=cs348_project
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "npm install && node loaddata.js"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
  mysql_data: