# docker-compose.yml
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ELHDD.J!w9bdNnL-
      MYSQL_DATABASE: cs348_project
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
