# docker-compose.yml
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    command: --secure-file-priv=""
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: cs348_project
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./cleanedsports.csv:/docker-entrypoint-initdb.d/cleanedsports.csv

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
